# AutoScan Yaml Config
thirdparty: # 路径必须配置在当前目录下，不可自定义当前执行文件以外的其他目录
  ObserverWardPath: /thirdparty/observerWard/observer_ward_mac_amd # observer_ward 可执行文件
  ObserverWardDir: /thirdparty/observerWard/ # observerWard 所在目录
  WebFingerprintPath: /thirdparty/observerWard/web_fingerprint_v3.json # fingerprintHub指纹库
  GeoLite2Path: /thirdparty/cdnCheck/GeoLite2-ASN.mmdb # ip相关
